language: objective-c

osx_image: xcode8.3

env:
global:
- LC_CTYPE=en_US.UTF-8
- LANG=en_US.UTF-8

before_script:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild clean build test -workspace Tests/AGSnapshotHelper.xcworkspace -scheme AGSnapshotHelper -sdk iphonesimulator -destination "platform=iOS Simulator,OS=10.3,name=iPhone 7" GCC_GENERATE_DEBUGGING_SYMBOLS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES | xcpretty -c

after_success:
- bash <(curl -s https://codecov.io/bash)
